### ISSUE TITLE
just a starter

### ISSUE THREAD

**Issue by figuerres** [AckerApple/angular-file#1]
ok now we can rock!

**Comment by AckerApple** [comment]
thanks for the support good guy!

**Comment by AckerApple** [comment]
ALSO, big fan of actual faces as icons. Good to see your face

**Comment by figuerres** [comment]
Hey a few notes just to let you know what i am up to and background:
I work for a company in Florida that does package delivery in the southeast US.
we have a very small IT team and are working on a large system project to work with Google Maps, planning delivery areas , tracking packages, billing and so on...

one small item is we want to have a custom Wiki to store a lot of documentation  so i am in the early stages of a side project Angle Wiki  https://github.com/figuerres/AngleWiki

I am really new to the Github and Angular stuff but have about 30 years of system development background, i am working with .Net to build Web api's  and with Identity Server for user sign on.
SQL 2016 for Sql data and we have some mix of NoSQL and SQL in parts of the system.

the idea with angle Wiki is to put out a core for building a wiki  that uses some common parts 
i have put in a markdown package and i am working on using a treeview to edit a wiki table of conent
to add to the page views, the file upload to add images and other documents to be linked into the wiki.
and identity server login that can be used or swap to any other provider like google / facebook / Microsoft.

**Comment by AckerApple** [comment]
I am in Florida too. You hiring? I've been at this for 20 years. Started with ColdFusion. Happily employed in Delray.

Ya'll hiring? If 130k salary doesn't make ya choke on your breakfast, lets talk? I'm considerably the best Florida has to offer.

It didn't seem you had any questions but if you did do let me know. I'm all about being dedicated to Open Source software engineering.
