### ISSUE TITLE
Consider removing ngFileUploader

### ISSUE THREAD

**Issue by AckerApple** [AckerApple/angular-file#12]
I think we should remove and technologies that aide in transmitting files.

Issues this is causing:
- People that don't know how to use HTML5 FormData, often come here thinking they need some heavy lifting file transmitter when they only need Angular+FormData
- It is too costly to maintain an Http transmitter
- The built-in file transmitter send multiple files as multiple single requests
- It gets confusion trying to match input name attributes with FormData POST names. People that do not transmit as file name input "file", think the input name should be the FormData name. That's a stretch.

Does anyone wish to offer input on this subject matter before I get another issue report and rip out all the file transmitting parts of this library?

**Comment by AckerApple** [comment]
We are requesting people to control the transmission as such:

```
import { HttpClient, HttpRequest, HttpResponse, HttpEvent } from '@angular/common/http'

class MyMyMyWhatDoWeHaveHere{
  
  constructor(public HttpClient:HttpClient){}

  sendArrayOfFiles(files){
    //HTML5
    const formData:FormData = new FormData()
     
    //Transmission POST name, file-contents, file-name
    files.each( file=>formData.append('file', file, file.name) )

    const req = new HttpRequest('POST', this.url, formData, {
      reportProgress: true
    })

    return this.HttpClient.request(req)
    .subscribe(event=>{
      if (event instanceof HttpResponse) {
        console.log('request done', event)
      }
    })
  }
}
```

**Comment by figuerres** [comment]
HttpClient  ++  also Angualr is now V5 and they have started to make note o the change and ask that the old gets depriciated.
[Angular 5 released](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced)

**Comment by AckerApple** [comment]
All my Http requests go through just one service. NOT one service and this little package that has an ngfUploader TEMPLATE-TO-TRANSMISSION component. If I was to upgrade this package to do more than selecting files, it would do me no good as I know better than that. It's too difficult to control the basehref and security headers of a template-to-transmission driven component.

We so need to remove ngfUploader from this library.

I like things simple too but this package is over extending itself and helping people go down the wrong path.

**Comment by AckerApple** [comment]
Shoot too, I just saw Angular HttpClient is NOT in the core it's in the common. Which is common but it's not ALWAYS.

HMMMMmmmmmmm. Again, I think we do need to remove ngfUploader. Sooner than later too. Agh, too much to do but I think I can fit in soon.

ONLY the sample code shows ngfFileUploader. It's been completely removed from the demo code

**Comment by figuerres** [comment]
for the folks who want examples of the back end i can make a small asp.net / web api example that is very small and simple.
if you want to put that here let me know.  we can't cover every case but two or three might be good.

**Comment by thetravis** [comment]
Btw, the [project page](https://github.com/AckerApple/angular-file) still has

"Easy to use Angular2 components for files upload http://valor-software.github.io/ng2-f…"

above the file listing with a link to the demo of an old version.

**Comment by AckerApple** [comment]
AHHHHHHHHHHhhhhhhhhhhhh, much appreciate you pointing that out to us. I will fix that type right away

**Comment by thetravis** [comment]
For the back-end I can try and provide a minimalistic example on NodeJS & Express now that it seems to work.

**Comment by AckerApple** [comment]
I welcome the documentation for server examples. They will need to be stand-alone markdown files. They will be linked to from the main README.md

I can't shake a stick at it enough => It would be hella tight like a tiger if yall would help via pull request.

Thanks much all around, great contribution here. I am working on the project right now adding new directive ngfFormData that will aide in casting files to FormData via syntax as such:
```
<ngfFormData [files]="filesModel" postName="file" [(FormData)]="myFormData"></ngfFormData>
```

**Comment by AckerApple** [comment]
We are now on 0.3.7 and docs have been heavily updated and example too

**Comment by figuerres** [comment]
when i get to a point where i can i will  ... just trying right now to finish my Wiki Project!!

**Comment by alignsoft** [comment]
A couple of things that may need clarifying in the examples/docs here:

`https://ackerapple.github.io/angular-file/`

Should there not be an import of ngfModule/ngf?

`       import { ngfModule, ngf } from "angular-file"`

I'm assuming so, as it's included in this example here:

`https://github.com/ackerapple/angular-file
`

In the example code, when using VSCode, this displays a TypeScript error:

`       httpEvent:HttpEvent<Event>
`

The error displays here:
`"Type 'HttpEvent<{}>' is not assignable to type 'HttpEvent<Event>'"`

```
      event => {
        this.httpEvent = event
```

Changing the type from `<Event>` to `<any>` resolves the error, but likely isn't the best solution.

It would be helpful to note that you need to import HttpClientModule into your module.ts

`import { HttpClientModule } from '@angular/common/http';`

Also,     `console.log('x', this.sendableFormData)` doesn't display anything, and the likely-supported-in-the-future     `console.log('x', this.sendableFormData.entries())` isn't actually supported in most browsers yet, so I'm not sure if there's any way to view the contents of FormData on the console.

I've implemented this example in a project exactly as I've understood from the documentation, and everything behaves the way I would expect, except where the live demo returns status 'OK' after uploading, I get `"SyntaxError: Unexpected token F in JSON at position 0 at JSON.parse"`, and I'm unclear if I'm missing something, or if there's something that's been coded in the live example that's different from the actual example code in the docs.

**Comment by AckerApple** [comment]
1. No ngf is not a required import. It’s only imported in the example for type checking (ngf:ngf)
2. Http<Event> passes type checking in angular typescript compiler, for my projects. I’m guessing you maybe missing some basic (a)types in node_modules folder
3. I think including HttpClientModule is in the main README examples. I will double check. Not going to document this more than beyond the examples.
4. I dont care how FormData cant be console logged. I dont. Send the files, check your network console log.
5. It seems your server is expecting a JSON body. Most all of the time, when sending files, a request body does not exist and instead a multi file post parser is needed. You can transmit both files and a body but the error you are receiving is an expected JSON yet you are most likely only sending files. Is my guess.

**Comment by alignsoft** [comment]
Thanks for the quick response!
1. All good!
2. Can you share a snippet from your package.json showing the relevant @types?
3. I'm just thinking about lowering the friction for someone new looking to make use of the package. There has to be some assumption of knowledge, but HttpClientModule is something you might expect to be already included, so noting it's a separate import might save someone some frustration.
4. I'm not worried about not being able to console.log the FormData, I only mention it because there's a     `console.log('x', this.sendableFormData)` in the example code, and it won't do anything. Maybe replace that with `console.log('Files in this.sendableFormData: ', this.files)` instead? 
5. For testing, until I wire up a backend service to receive the files, I'm using the same `url = 'https://evening-anchorage-3159.herokuapp.com/api/'` you're using in the example, and that's where I'm seeing the error. I'd expect to get the same response as when I run the same uploaded files through your example, which is why I'm wondering where the difference is. You may be sending to your own url in the actual running code, and just not listing that url in the example, but that's not clear.

**Comment by AckerApple** [comment]
2. It maybe a combination of **@types**, included packages, and/or tsconfig
2.1 All dependencies, [can be seen here](https://github.com/AckerApple/angular-file/blob/development/package.json#L53)
2.2 One of these two tsconfig files may help you: [tsconfig.json](https://github.com/AckerApple/angular-file/blob/development/demo/src/tsconfig.json) or [tsconfig.aot.json](https://github.com/AckerApple/angular-file/blob/development/demo/src/tsconfig.aot.json)
3. (I'm always super direct, here it comes) Put a pull request where your mouth is. Instead of me assuming where best to document and you maybe bauk at it => you do the work, I'll pull your code.
4. After I hit "Comment", I'll goto the code and review for removal
5. The [angular-file demo page](https://ackerapple.github.io/angular-file/), when Upload All is tapped, sends files and network console shows "File is uploaded". Where the files are sent in demo, is left over code from when I forked. In my production code, I have both Angular Http and Angular HttpClient being used. They work great and easy to post to some Java backend in one app and a NodeJs server on another. Good luck transmitted files.

**Comment by AckerApple** [comment]
the console log of sendableFormData will be removed the next time i bundle and deploy the code

**Comment by alignsoft** [comment]
3. Re: (I'm always super direct, here it comes) Put a pull request where your mouth is. Instead of me assuming where best to document and you maybe balk at it => you do the work, I'll pull your code.

Sounds like a plan! Cheers!

**Comment by Zawmoewin** [comment]
Good.©©©©©©®®®®®®©©©©©©©©©©©©©

**Comment by AckerApple** [comment]
OH MY OH MY!!!!!! I finally flippin' did it!!!!!!!!!!

FileUploader class has been completely removed from angular-file as of 0.5.0

```
## 0.5.0 - (2018-02-07)
- Removed much unused code from original package that this is a fork from
- Fixed and ensured accept attribute working correctly
- Improved demo page in terms of the accept attribute and file drag metadata
- BREAKING CHANGES
  - Removed directive ngfUploader
  - ngfUploader.directive.ts has been removed from this package
  - FileUploader.class.ts has been removed from this package
  - FileUploader.class has been removed from this package
  - FileItem.class has been removed from this package
  - FileLikeObject.class has been removed from this package
  - Files are always considered valid when dragged inside browsers that dont allow ANY drag file metadata
  - Input forceFilename has been removed from all ngf directives
  - Input forcePostname has been removed from all ngf directives
```
