### ISSUE TITLE
filesChange event emitter

### ISSUE THREAD

**Issue by twilczak** [AckerApple/angular-file#15]
Hi, 
Thanks for the library, looks like you're making good progress with it. 
I am wondering if you're going to add filesChange as a documented output for ngf directive?

Looking through the back issues and your comments, it appears to be a recent addition, in which case it simply may be the case that the documentation wasn't updated to reflect the new event emitter? 

It is listed as an option in the upgrade section, but isn't listed as one of the available ngf attributes. 

Mainly trying to figure out if this is going to be an officially supported option, or if it's only there for the upgraders.

**Comment by AckerApple** [comment]
Hey yo, it absolutely is documented as Ann attribute here: https://www.npmjs.com/package/angular-file#ngf-directive

[(files)] means [files] and (filesChange) just like [(ngModel)] means [ngModel] and (ngModelChange)

**Comment by AckerApple** [comment]
Source code: https://github.com/AckerApple/angular-file/blob/development/src/file-upload/ngf.directive.ts#L32

**Comment by twilczak** [comment]
Alright, I wasn't aware there was an implicit convention here. 
I did pick it up from the source and the upgrade docs, and am using it. 

Thanks again

**Comment by AckerApple** [comment]
Sure, glad I could help.

Two way binds require appending “Change” to the output emitter. Angular thing
