### ISSUE TITLE
Cant get ngfFormData to update formdata

### ISSUE THREAD

**Issue by ronnyek** [AckerApple/angular-file#20]
So I'm trying to replicate the example at: https://ackerapple.github.io/angular-file/

I had the uploadFiles() getting triggered from (filesChange), which seems like it fires to early to have done anything at all with the files collection.

I went ahead and set it up for manual triggering to upload to more closely match your example. SendableFormData is no longer undefined, but looks like an empty object. If I set a breakpoint in the upload click event, this.files contains one entry, sendableformdata is {}.

I was curious if you had any ideas there... and as soon as I get that resolved,  I was wondering if there were events someplace I could subscribe to, that would let me get the sendableFormData at an appropriate time where its been updated.

**Comment by ronnyek** [comment]
Apologies, this was one of those things where I struggled with it for a while, and as soon as I post this message I come up with the solution on my own.

Just in-case anyone else runs into this... the filesChange event sends the files. You can pass that directly into the examples upload files. I constructed the formData manually like so:
```
 const formData = new FormData();
    for (let i = 0; i < files.length; i++) {
      formData.append('file', files[i]);
    }
```
And then just pass that to the httprequest, instead this.sendableFormData. It now uploads files on drop.

**Comment by AckerApple** [comment]
Yes ngFormData is completely extra and typically unnecessary.

However, I think you'd benefit from using the two way bind of `[(files)]` instead of the one way bind expression you are using `(filesChange)`. I gathered this recommendation from some of the things you mention about "too early" and "empty object".

Glad you figured yourself out

**Comment by AckerApple** [comment]
[(files)] is equal to [(ngModel)]

as

(filesChange) is equal to (ngModelChange)
