### ISSUE TITLE
accept restriction file type not working

### ISSUE THREAD

**Issue by bhanukumar04** [AckerApple/angular-file#22]
with out adding accept restriction, control is going to  filesSelect() method in the below code and am able to the uploaded file.  if I need to add restriction for file type its not working .

component.html file: 
 <span ngfSelect multiple="1" [(file)]="file"  (fileChange)="filesSelect(file)" [accept] = "accept" >Browse</span>

component.ts file:

 accept = '.pdf, .jpg, .tif, .gif, .bmp, .jpeg'

**Comment by AckerApple** [comment]
I’ll get back to you. I have a couple of concerns from your code example

**Comment by AckerApple** [comment]
The accept attribute has been confirmed working. You will need to elaborate and convince me how it is NOT working.

Demo page used to confirm accept working: https://ackerapple.github.io/angular-file/

Screen shot of confirmation that accept is working (attached):
![acceptworking](https://user-images.githubusercontent.com/7964429/35923530-8411778c-0bee-11e8-94ce-42b715126968.png)

**Comment by AckerApple** [comment]
This package in use by many in production, including myself, with the accept attribute working just fine. I highly doubt such an important attribute is failing.

Good luck figuring yourself out

**Comment by AckerApple** [comment]
OK UPON CLOSER INSPECTION, I am finding the demo to be misleading and I THINK I might see an issue.

Also, the "Combo drop/select" image only zone is pre-hardcoded for image only so I'm not testing this right... Will report

**Comment by bhanukumar04** [comment]
@AckerApple  Thank you for the Quick Reply.

I have created a sample project to show with and without  file filtering types. 
when there is no filter for file types and you select any file it will display the file name. 
when there was filtering for certain types here i considered  '.pdf, .jpg, .tif, .gif, .bmp, .jpeg' .In browse it will show only the restricted file  as expected  but when you select any file it wont show the result as above one.
If am passing the accept as wrong way let me know.
https://stackblitz.com/edit/angular-x4abqm

**Comment by AckerApple** [comment]
I believe to be experiencing the same issue as you. But problem was too much convoluted code from the original package I have forked from.

I think I am 30 minutes away from version 0.5.0 which finally gets rid of old bad logic from original package before I forked.

Will report shortly

**Comment by AckerApple** [comment]
I have vastly improved the entire package.


```
## 0.5.0 - (2018-02-07)
- Removed much unused code from original package that this is a fork from
- Fixed and ensured accept attribute working correctly
- Improved demo page in terms of the accept attribute and file drag metadata
- BREAKING CHANGES
  - Removed directive ngfUploader
  - ngfUploader.directive.ts has been removed from this package
  - FileUploader.class.ts has been removed from this package
  - FileUploader.class has been removed from this package
  - FileItem.class has been removed from this package
  - FileLikeObject.class has been removed from this package
  - Files are always considered valid when dragged inside browsers that dont allow ANY drag file metadata
  - Input forceFilename has been removed from all ngf directives
  - Input forcePostname has been removed from all ngf directives
```

**Comment by bhanukumar04** [comment]
I have updated to latest version 0.5.0, around accept filtering still the same issue . Check the below sample example for this scenario.
https://stackblitz.com/edit/angular-x4abqm

**Comment by AckerApple** [comment]
Your example page is working for me. See attached image where some files are grey for filtering

![image](https://user-images.githubusercontent.com/7964429/35934039-615c8832-0c0a-11e8-8672-41b641b0c99d.png)

**Comment by AckerApple** [comment]
Using Chrome on Mac

**Comment by bhanukumar04** [comment]
with out filtering when you browser for any file , it will display the file name as selected file is :  ' file name '. 
when you click on the filter browser link, it will show with filtering  and when you select file it will not display the file name.
you can check and let me know after browse select file in both cases.

**Comment by AckerApple** [comment]
Please reply with a very concise description of ONLY the expected behavior that is NOT occurring as you wxoect

**Comment by AckerApple** [comment]
*expect

**Comment by bhanukumar04** [comment]
when applied accept value as '.pdf, .jpg, .tif, .gif, .bmp, .jpeg'  and  browsed the files,  it was filtering as expected but after file selected from browse,   if we listen to **fileChange** Event Emitter , we are not getting the selected file.
If we are not applying  file filtering,  in **fileChange** Event Emitter we are getting the selected file.

**Comment by AckerApple** [comment]
Ok, digesting

**Comment by AckerApple** [comment]
I fixed it. Thank you much for providing example page to help me get it right.

Aquire 0.5.1

Would you believe it was the spaces between your file names?

**Comment by AckerApple** [comment]
Also, try using [(lastInvalids)] or (lastInvalidsChange) ... It led me to knowing the system had selected files but that the component considered them invalid

**Comment by bhanukumar04** [comment]
@AckerApple  its the space issue between the files, when I removed space its working as expected.
Also  lastInvalidsChange is working as expected. 
Thank you once again for the quick response.

**Comment by AckerApple** [comment]
Awesome. Makes me happy.

Please star, follow, or perform any social actions that will naturally boost the popularity of this package.

And go ahead and close this issue if satisfied
