### ISSUE TITLE
I need a (change) function to detect if there is new file selected.

### ISSUE THREAD

**Issue by manpreetpc** [AckerApple/angular-file#25]
I need a (change) function to detect if there is new file selected.

**Comment by AckerApple** [comment]
It’s (fileChange) and (filesChange)

You’re going to need a lot more help if you couldn’t find that

**Comment by AckerApple** [comment]
I also have a sassy mouth so I do apologize for such a sharp comment. But please don’t waste my time on something so simple. I put out lots of free code but I’m no hand holder

**Comment by rangedsp** [comment]
Do you mind updating the README wrt (fileChange)? Kinda weird that's not there considering the other events are.

**Comment by AckerApple** [comment]
[(ngModel)] is ngModel="" and [ngModel]="" and (ngModelChange)=""

I absolutely will NOT be documenting a well known Angular implied technique

**Comment by AckerApple** [comment]
Closed issue on accident. I prefer the reporter close the issue when satisfied
