### ISSUE TITLE
ngfBackground no preview image showing

### ISSUE THREAD

**Issue by johnfrades** [AckerApple/angular-file#26]
Hi, i copied the demo code but on my local machine, everytime i attach an image, it only shows the name, not the preview thumbnail

**Comment by AckerApple** [comment]
It’s works in the demo.









Now, if that was my only messag, wouldn’t that suck for help? Listen, you’re giving me next to nothing to work with here. This package is in use by many AND especially in production by me.

It works. Try to give me details, a plunker, ah anything more than a story.
