### ISSUE TITLE
"fileDropDisabled" option of "ngf" is not working for file drop.

### ISSUE THREAD

**Issue by karolis-k** [AckerApple/angular-file#30]
If I set it to true, it disables, file selection, but not file drop.

I looked at source code and for me it seems that check is missing in `ngfDrop` event. I think it should be something like this:
```javascript
  @HostListener('drop', ['$event'])
  onDrop(event:Event):void {
    this.closeDrags()
    // Condition below added:
    if (this.fileDropDisabled){
        return;
    }
    let files = this.eventToFiles(event)

    if(!files.length)return

    this.stopEvent(event);
    this.handleFiles(files)
  }
```
P.S. naming for this property seems to be not correct, or it should belong to `ngfDrop` rather than `ngf`.

**Comment by AckerApple** [comment]
Will let ya know

**Comment by dellc64** [comment]
Hi. Any progress here?

**Comment by AckerApple** [comment]
If y’all need this, make a pull request. I don’t need it and I’m swamped

**Comment by AckerApple** [comment]
#46 looks great. I’ll merge and deploy no later than Monday. Thank you a lot @dellc64

**Comment by AckerApple** [comment]
Completed
