### ISSUE TITLE
custom angular validator for ngfDrop [question]

### ISSUE THREAD

**Issue by karolis-k** [AckerApple/angular-file#31]
Hi,

I am not very experienced in Angular, but as far as I understand it's possible to write validation (or add built in validation, like 'required') for this input:
`<input type="file" ngf [(file)]="file" />`

But is it possible to do the same for ngfDrop, like here:
```
<div ngfDrop
  [(files)]="files"
  [(file)]="file"
  ([validDrag])="validDrag"
  ([invalidDrag])="invalidDrag"
  [ngClass]="{'myHoverClass': validDrag, 'myAntiHoverClass': validDrag}"
>
  Drop Files Here
</div>
```
?

**Comment by AckerApple** [comment]
Your answer requires time to explain and change your perception on how to achieve the job you are looking to achieve.

I don’t got that kind of time. Do the work yourself. Don’t rely on some html based attribute to validation your shit

**Comment by karolis-k** [comment]
Sure I understand that you don't have time to elaborate this, but basically the answer required for this question is just yes or no. I don't think it requires too much time to answer that.

I implemented my solution for this, but I'm not happy with it. I just wanted to know if I could have done it according to the angular guidelines:
https://angular.io/guide/form-validation#adding-to-template-driven-forms

**Comment by AckerApple** [comment]
“Just a yes or no”. If it’s just that then yes but if yes is not right then no.

It’s “just” that easy......
