### ISSUE TITLE
(lastInvalidsChange) get invalid file

### ISSUE THREAD

**Issue by issy123** [AckerApple/angular-file#32]
Hi,

So I have found out that there is an lastInvalidsChange event in the code (https://github.com/AckerApple/angular-file/blob/development/src/file-upload/ngf.directive.ts#L26).

using it like so: `<div ngfDrop (lastInvalidsChange)="lastInvalidsChange(file,type)"></div>`

Now when I try it out I neither get the invalid file as parameter and neither is the lastInvalids array updated.
using `"angular-file": "^0.5.4",`. and Angular 5

The only fix I was able to pull out was to wrap it around a setTimeout to get the updated array like so:

```
setTimeout(()=>{
  console.log("invalid files updated",this.lastInvalids);
},1);
```

Am I missing something? Or is my 'fix' atm the way to go?

**Comment by AckerApple** [comment]
The demo page worked for a quick test of invalid files. I know it works. On the road. Y’all later
