### ISSUE TITLE
Limit number of files to upload

### ISSUE THREAD

**Issue by cunundrummer** [AckerApple/angular-file#34]
After checking the docs and readme, I have come to the conclusion that I cannot limit the number of uploads a user is allowed to upload through a directive.  

I've implemented everything like in the demo, and have it working. I tried a few things through the component and template, but excess files are always remain in the queue.  I checked through the src files and believe that [in the ngfDrop directive](https://github.com/AckerApple/angular-file/blob/development/src/file-upload/ngfDrop.directive.ts) it can be implemented. Specifically here (line 29 in link):

```
@HostListener('drop', ['$event'])
  onDrop(event:Event):void {
    this.closeDrags()
    let files = this.eventToFiles(event)

    if(!files.length || **files.length > MAX_FILES**) return;  **// ex. const MAX_FILES = 9;** 

    this.stopEvent(event);
    this.handleFiles(files)
  }
```

or even in [ngf directive](https://github.com/AckerApple/angular-file/blob/development/src/file-upload/ngf.directive.ts) as an @input().  

Finally, my question is, is there something I am missing or 'limiting number of files' not implemented?  If not, can this feature be implemented?

**Comment by AckerApple** [comment]
It appears no file number limiting binding exists but this is so something you could and maybe should control on your end. You have access to the files model. You could manipulate the array of files.

I’ll either need a pull request or more requests for this feature for me to go out of my way for it

**Comment by cunundrummer** [comment]
Found possible hint to a solution in the ngf.directive -> 
```
initFilters(){
    //this.filters.unshift({name: 'queueLimit', fn: this._queueLimitFilter})
}
```

**Comment by AckerApple** [comment]
What help do you need to make a pull request?

Perhaps you could fork, uncomment anything related to `queueLimit`, build, local browser test, and then issue a pull request.

I'm busy with paid projects. If you need this, I'm going to need help

**Comment by awojtczyk** [comment]
Maybe not the best way, but you can use something like this:
`(filesChange) = "restrictToMax(4)"`
and
```javascript
restrictToMax(i) {
    this.files = this.files.length > i ? (this.files = this.files.splice(0, i)) : this.files;
} 
```
So only the last 4 images will show up.

**Comment by webplease** [comment]
> Found possible hint to a solution in the ngf.directive ->
> 
> ```
> initFilters(){
>     //this.filters.unshift({name: 'queueLimit', fn: this._queueLimitFilter})
> }
> ```

Hi cunundrummer,

have you found a solution for limit the file's number?
