### ISSUE TITLE
Type of "CSV" files not recognize 

### ISSUE THREAD

**Issue by SimonKnu** [AckerApple/angular-file#35]
Hi, nice work !

However, I think that some type of files are not recognize by angular-file (.db, .sql, .ttf, .csv, .log)
![image](https://user-images.githubusercontent.com/32613796/49936156-7fc56e80-fed3-11e8-9c3e-cba69dfa225c.png)
![untitled](https://user-images.githubusercontent.com/32613796/49936177-8f44b780-fed3-11e8-9827-e87fe00cdf25.png)

IMO, some mime types are missing... like "text/csv","application/csv","application/vnd.ms-excel","text/x-csv","application/x-csv"

Is your list not complete ? Or am I missing something ?

Simon

**Comment by SimonKnu** [comment]
Thanks for the answer

No, I use Firefox..

I have one last question just for my clarification
Who determine the file type (see picture) when they are dropped ? Is it your composant (angular-file) or the browser ?
![untitled](https://user-images.githubusercontent.com/32613796/49946105-8e6d4f00-feee-11e8-806f-01a716b15f26.png)

Thanks again

**Comment by SimonKnu** [comment]
Thanks for the answer

No, I use Firefox..

Maybe you answered to this and I didn't get it but I have one last question to clarify my thoughts...
Who determine the file type (see picture) when they are dragged or selected ? Is it your composant (angular-file) or the browser ?
![untitled](https://user-images.githubusercontent.com/32613796/49946735-df317780-feef-11e8-95b8-085b4e84997b.png)


Thanks again :)

**Comment by AckerApple** [comment]
It is the browser that reveals the mime type. Standards exists for how the whole reading of files goes in a browser. This package, angular-file, essentially wraps all the adhering of standards for browser file reading into an Angular package.

For the mime type, this package, just takes what the browser gives it during select/drag/drop and then it does it's best to see if mime types match occurs as follows:

1. This package tries an exact mime match as seen in this code:
  - https://github.com/AckerApple/angular-file/blob/development/src/file-upload/fileTools.ts#L22
2. This package tries to match by file extension as seen in this code:
  - https://github.com/AckerApple/angular-file/blob/development/src/file-upload/fileTools.ts#L28

All of the above mentioned mime type comparing and parsing, is unit tested in this code here:
https://github.com/AckerApple/angular-file/blob/development/src/file-upload/fileTools.spec.ts

Please let me know if you have additional input, see a mime type comparison issue, love pinball, or let me know anything else I can help with
