### ISSUE TITLE
Accepted ".xls" files are seen as invalid drag but gets in the array anyway

### ISSUE THREAD

**Issue by gabrielcs23** [AckerApple/angular-file#37]
Hey, first of all thanks for taking the time to mantain this awesome project

My problem is, when I set accept to ".xls", wich translates to application/vnd.ms-excel mime type, drag and drop sees this as an invalid drag, wich shouldn't happen, but puts the file on the files array anyway. Can be reproduced on the demo page

![upload-excel](https://user-images.githubusercontent.com/13492277/50344599-cdb12680-0512-11e9-853a-99d732cd7c9a.png)

No problem using the ngfSelect directive, the files is there for me to select it

**Comment by AckerApple** [comment]
Oh yeah, and try different browsers and different mime types. As I seen in screen shot you only have .xls which would require reading the file name and the browser doesn't get the file name until drop.

I bet that will fix you up... Use the mime type `application/msexcel` and/or `application/vnd.ms-excel`

**Comment by gabrielcs23** [comment]
The screenshot was taken on Chrome. Other file extension like  `.png` or `.jpg` or even `.xlsx` (more recent version of excel sheet) works as it should. Looks like only `.xls` is having this issue.

I am trying to stop to use mime type at all and start using file extension as it is supported by angular-file so that way I can show a screen message to my user informing the correct type of file he can upload without having to hard code / decode the mime type string for that message because a normal user can't understand most mime types.

I've made a workaround changing almost everything to use file extension. But I have to still use `application/vnd.ms-excel` instead of `.xls` so the drag and drop doesn't show as invalid and that way I have to check for that string and show on screen that the user can upload a `.xls` file

Same thing happening in Firefox and Edge

Hope I've managed to explain the issue

**Comment by AckerApple** [comment]
Yep, I fully understand but it's not an issue as you perceive it.

This package, during drag, at best gets only access to the mime type. NOT the file name. So if you are thinking you would like to get away from mime types, not gonna happen.

This package, due to browser security, only gets the file name on drop/select. So again, if your target is getting drop right, you must use mime type definitions.

Lastly, use stars where possible. "image/*" versus "image/png".
