### ISSUE TITLE
Extension warning before size warning

### ISSUE THREAD

**Issue by issy123** [AckerApple/angular-file#39]
When someone uploads an big file and also is not the accepted extension it should warn about that the filetype is invalid before it warns about the size is too big.

Otherwise the user would first shrink a file and then get's the news that his file type is not accepted

**Comment by AckerApple** [comment]
That seems fairly logical. I’d accept a pull request for that

**Comment by hydiak** [comment]
https://github.com/AckerApple/angular-file/pull/43

**Comment by AckerApple** [comment]
Fixed in 1.0.0
