### ISSUE TITLE
Security / Scenario Test - Manually changed extension are getting uploaded easily

### ISSUE THREAD

**Issue by aakash1401** [AckerApple/angular-file#40]
Hi,

Thank you for this amazing library.

Recently i was testing a Security Scenario included by my lead.

What I do I want to upload only .XLSX type extension ( let's say 2 MB ). I go to folder and modify its file type manually to .png or .jpg.

I go to demo page and I upload this file in jpg format. 

![image](https://user-images.githubusercontent.com/31201591/50676768-2a850480-101c-11e9-8433-f08fca4c2022.png)

If my application is allowing to upload only valid image files, how do I make sure for above manually converted file type ( .xls to .jpg ) it throws an error and shows message like it is an invalid file. Right now it is uploading it without any issue.

Thank you.

**Comment by figuerres** [comment]
honestly i would view any client side values for file name, extension and mime type / content type as suspect. one could use tools to post data where the content may be very different from what the headers say it is. the only sure bet is to inspect the content for a known value.  a real pain for sure but if you are talking "security"  then that is the only sure way to filter out the bogus uploads with bad payloads.

**Comment by aakash1401** [comment]
That is correct @figuerres as long as security is concerned. Initially we had implemented this requirement like handling these validation on Back end side which would not be feasible. Back end would not accept any bogus or manually changed files.

I feel it is better to validate such issues on Client side itself.

@AckerApple I do understand about adding / checking tedious validations about MIME types. There might have similar or another approach to this solution. 

I would also look for such solutions. Till then, Please accept it as Pull request. It would solve many developers' nightmares for file uploads.

Thanks.

**Comment by AckerApple** [comment]
“It would solve many developers' nightmares for file uploads.”

“I feel it is better to validate such issues on Client side itself.”

Those are bad drama filled statements. Your github icon is a murderous video game character. Your github history is next to none. You are starting to push buttons.

I know what I’m doing and talking about. You ALWAYS have to rely on server side validation and client side validation is only a convenience.

If you want the ability to disable file extension checking, I’m going to need you to issue a pull request. I’ve not had anyone else mention this before.

**Comment by digeomel** [comment]
@aakash1401 👎 
@AckerApple is right, you have to do this in the back-end, unless you want to roll-up your own front-end content analysis library. We did this in the past in one of the projects I worked on using the Apache Tika library: https://tika.apache.org/
I suppose it could be done in the front-end with the File API (not sure about it being cross-browser, though), but this has nothing to do with the file upload component, it is a (big) project on its own.
