### ISSUE TITLE
Click on dropzone doesn't work

### ISSUE THREAD

**Issue by hydiak** [AckerApple/angular-file#44]
After these [changes](https://github.com/AckerApple/angular-file/blame/development/src/file-upload/doc-event-help.functions.ts#L30), click on dropzone won't show select-file-dialog

because `clickHandler` is expecting null from `detectSwipe` method:
https://github.com/AckerApple/angular-file/blob/79e3a71f14e6c8e9db579bfd716f19da13c54bda/src/file-upload/ngf.directive.ts#L199

**Comment by sjyn** [comment]
I just came here to open this issue. Currently backing down to version 0.5.9 makes it work, but we'd like to update our dependency as soon as possible.

**Comment by AckerApple** [comment]
reviewing. Trying to break down code differences

**Comment by AckerApple** [comment]
Thank you much. v1.0.2 has been release. Please confirm and then close issue

**Comment by AckerApple** [comment]
@hydiak, thank you again for your help. I have made you a collaborator of this package.

If you have time and if you are into Angular animations, I would appreciate your review of my animations package [ack-angular-fx](https://www.npmjs.com/package/ack-angular-fx)

Go open source!

**Comment by hydiak** [comment]
> Thank you much. v1.0.2 has been release. Please confirm and then close issue

confirmed.  thanks

**Comment by hydiak** [comment]
> @hydiak, thank you again for your help. I have made you a collaborator of this package.
>
You are welcome! 
> If you have time and if you are into Angular animations, I would appreciate your review of my animations package [ack-angular-fx](https://www.npmjs.com/package/ack-angular-fx)
> 
I'm new with angular, but i'll give a try
