### ISSUE TITLE
Http and HttpClient  : future path

### ISSUE THREAD

**Issue by figuerres** [AckerApple/angular-file#5]
just wanted to drop a note that i see that http is beeing replaced by HttpClient in the angular 4.3 / 4.4 releases.

ran into this last week when i was working on some code for Http Interception to pass JWT tokens to service calls.

the new HttpClient  has the option of an Interceptor so that no added packages are needed.
but the  old Http does not see the new Interecptor .

just wanted to make note of this and that we may at some point need to have two versions of the angular-file and or a need to document which Http is used and the effects of it.

**Comment by AckerApple** [comment]
Thanks. I'll put this on my radar as this is the first I am hearing.

**Comment by AckerApple** [comment]
Relevant stack article: https://stackoverflow.com/questions/45129790/difference-between-http-and-httpclient-in-angular-4

**Comment by AckerApple** [comment]
I think in general this is why its better to use [(file)] and [(files)] models with your own Http transmitter.

I don't use angular-file to transmit files. If angular-file is to change the way it transmits files, it wont break any of my project code as I know better than to have one package handle both the user file selecting and uploading process.

**Comment by figuerres** [comment]
Yeah this new HttpClient means a lot of small changes to switch to it.

**Comment by AckerApple** [comment]
It does seem small and for the betterment of Http. I like it. Wonder why they decided to include it in @angular/common? Yes, http is such a very common item but so is @angular/forms.

Thank you again for reporting

**Comment by figuerres** [comment]
Actually I think i know part of the story....  last year i was in Orlando at Vs live with John Pappa and Ward Bell, my self and others asked about the lack of an HTTP Interceptor in the framework. Ward said that they had some code but were not ready then.
so I think that they saw a need to add that and address other issues that were found with Http V1 in the first release.
PS, I should be there this year also; if you are going to be there we might meet up there.  Nov, 12 to 17 
[https://vslive.com/ecg/live360events/events/orlando-2017/vslive.aspx](https://vslive.com/ecg/live360events/events/orlando-2017/vslive.aspx)

**Comment by AckerApple** [comment]
Closing this issue. It has been determined NO http transmitters belong in this project. FileUploader class will be removed after awhile
