### ISSUE TITLE
Request: Share demo on StackBlitz

### ISSUE THREAD

**Issue by RezaRahmati** [AckerApple/angular-file#50]
Hi

I found out that the source for demo is not available any more, as well as during implementation I found out some functionalities are not working as demo (by my mistakes). It would be beneficial if you could create stackblitz of the demo and share it in your readme file, then we could have fork it and do some tests to make sure if it's a bug or we missed something

**Comment by AckerApple** [comment]
The source code for the demo is here:
https://github.com/AckerApple/angular-file/tree/development/demo/src

The demo page is here:
https://ackerapple.github.io/angular-file/
