### ISSUE TITLE
Bundlesize angular elements

### ISSUE THREAD

**Issue by tariva** [AckerApple/angular-file#51]
After implementing the package size of the prod build went from 3660KB to 4202KB.

I dont understand why this happens as only the lib was added to the package lock.

Here are my dependencies:
: {
    "@angular/animations": "^6.1.10",
    "@angular/cdk": "^7.0.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/elements": "^6.1.10",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/flex-layout": "^6.0.0-beta.16",
    "@angular/material": "^7.0.0",
    "@angular/material-moment-adapter": "^7.0.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@webcomponents/custom-elements": "^1.2.1",
    "@webcomponents/webcomponentsjs": "^2.1.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "document-register-element": "^1.7.2",
    "hammerjs": "^2.0.8",
    "moment": "^2.22.2",
    "rxjs": "^6.0.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "~0.8.26"
  }
 would be amazing if u could help me out thanks :)

**Comment by AckerApple** [comment]
I’ve been more than fairly aggressive with watching my deploy sizes. However it’s possible this package could use a more detailed review. 

This will take time to inspect. Will have to review the stats.json and then comb the files to ensure best tree shaking.

Pull requests welcome. I will report if I get some time today

**Comment by AckerApple** [comment]
I'm actively working on this. I see a lot of room for improvement

**Comment by AckerApple** [comment]
Please acquire version 1.2.1

This package was last bundled on Angular v5. Now 7

I also have created a stats page to see the bundle size and it size my src folder is 13k gzipped
https://ackerapple.github.io/angular-file/stats.html
