### ISSUE TITLE
Wrong maxSize

### ISSUE THREAD

**Issue by eggp** [AckerApple/angular-file#55]
Hello,

maxSize parameter calculation is wrong :( this not kbyte, just byte

The error can also be simulated on the example page
![image](https://user-images.githubusercontent.com/1015211/58193296-f8222e00-7cc2-11e9-8bdb-87aedd2810e6.png)

thanks
eggp

**Comment by AckerApple** [comment]
I have updated the demo page. You may have to clear cache or something to that effect.

Please close issue when satisfied

**Comment by eggp** [comment]
ok, thx

plz update input placeholder text ;)
