### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by cristian-g** [AckerApple/angular-file#59]
It seems that the heroku app is down, since the requests to upload files are returning a 404 error:
https://evening-anchorage-3159.herokuapp.com/api/

As a result, the demo isn't able to upload files:
https://ackerapple.github.io/angular-file/

**Comment by AckerApple** [comment]
Thanks I’ll look into it

**Comment by AckerApple** [comment]
Fixed.

Note to self: I hijacked the file upload url from this demo: https://blueimp.github.io/jQuery-File-Upload/
