### ISSUE TITLE
BUG: `ngfDrop` directive doesn't work with IE11

### ISSUE THREAD

**Issue by anield** [AckerApple/angular-file#6]
Drop a file on `ngfDrop` zone in IE11 and it will open in browser (default IE file drop action).

Can reproduce using demo site:
https://ackerapple.github.io/angular-file/

The original unforked `ng2FileDrop` directive still works fine with IE11 here:
https://valor-software.com/ng2-file-upload/

I did a small amount of debugging - it appears the `drop` event is handled by `ngfDrop.onDrop()` but `files = []` here:

```
let files = this.eventToFiles(event)

if(!files.length)return
```

**Comment by AckerApple** [comment]
Hmmmmmmm. Almost enough details but I can’t see what the error is. Can you try again or elaborate on what you think the problem is.

**Comment by AckerApple** [comment]
I’m guessing theirs no error but just no files get dropped?

**Comment by anield** [comment]
yeah no error - presumably the dropped files are not being unwrapped correctly inside `eventToFiles()`. I'll see if I can debug some more.

**Comment by figuerres** [comment]
i have not had time to check but one big thing that may be in issue is to make sure that you add the IE 11 polyfills in a new project, ie 11 does not have some script stuff that chrome has.
the other thing is some css things do not work on ie 11 that work on chrome and need work arounds.
that is the two main areas that tend to be the problem.

**Comment by AckerApple** [comment]
Please wait... typing. @figuerres, you're a genius

**Comment by figuerres** [comment]
sometimes yes, other times not so much.

**Comment by AckerApple** [comment]
I'm in the middle of something so I can't respond like I would like to. It is the polyfills. My example page doesn't have the polyfills.

I need to add the polyfills back in

**Comment by AckerApple** [comment]
Well actually now that I got a second to look, the polyfills seem like they should be in the example, as seen in this line of code for the demo page:
https://github.com/AckerApple/angular-file/blob/development/demo/src/index.ts#L1

It still could be a pollyfills thing though, just saying code suggests it should be there. ALSO, if it was a polyfill issue we'd have an actual error.

Hmmmmmmmmmmmm, leaning away from polyfill now

**Comment by anield** [comment]
I tried adding missing polyfills locally (we had most of them already) and it didn't seem to make a difference.

**Comment by AckerApple** [comment]
I only have a copy of IE11 at the office. I won’t be there till Monday and even then I gotta get someone else to get the machine turned on.

I used to use an online IE emulator. If you know how a Mac guy could easily test IE11, let me know

**Comment by figuerres** [comment]
Actually Microsoft does have a way to help
They publish free vm images of several versions of ie for multiple vm systems 
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
Might help.

**Comment by AckerApple** [comment]
Acknowledged. Good stuff. Will check it out tomorrow as today, Sunday, is filled

**Comment by figuerres** [comment]
Yeah, this weekend I have been doing neglected cleaning and water change on my 150 gallon saltwater aquarium,  what a pain....

**Comment by AckerApple** [comment]
The issue, is IE11 does not indicate the amount of files being dragged nor the types of files being dragged. It appears all other browsers, on drag over, reveal number of files and types.

So the fix I have NOT yet posted removes the files.length check as seen here:
https://github.com/AckerApple/angular-file/blob/development/src/file-upload/ngfDrop.directive.ts#L38

Fixed will be posted within an hour

**Comment by AckerApple** [comment]
Fixed in version 0.3.3 . Examples page updated . Please test and close issue or report more.

**Comment by AckerApple** [comment]
npm updated

**Comment by anield** [comment]
tests out ok in IE11 (and Chrome) - tks for the speedy turnaround.

**Comment by anield** [comment]
tests out ok in IE11 (and Chrome) - tks for the speedy turnaround.
