### ISSUE TITLE
Angular Universal error

### ISSUE THREAD

**Issue by stasdovydenko** [AckerApple/angular-file#62]
Angular 8.1.0, Angular Universal 8.1.0
When I try to naviate to any page it gives me this error (this happens even when the page does not contain any features from the ngfModule). It seems the issue occur when I import the ngfModule.
![image](https://user-images.githubusercontent.com/12597196/60888569-c27bd900-a25f-11e9-9e70-c014c75ea2ab.png)

**Comment by AckerApple** [comment]
You are missing type definitions for common JavaScript definitions such as for the one you are seeing an error for of “File”

I’m busy right now but you need to install OR tell TypeScript the correct types. The error you are seeing is because the compiler isn’t aware of all modern JavaScript types.

**Comment by stasdovydenko** [comment]
This happens only on the server side (we're using Angular Universal and server-side rendering for SEO support). On the client side everything works fine. So this error is only in the nodejs console. It doesn't matter if I use any of angular-file directives on the page or not, I think the problem emerges when I import the ngfModule. Also, the interesting thing is that this is the first error, and it emerges just once after the loading the app in the browser. After this error when I try to reload the page, there is another one:
![image](https://user-images.githubusercontent.com/12597196/60966007-f1598400-a31f-11e9-9ed1-c711384c7193.png)
And this error is shown every time when I reload the page.
It seems something in the code breaks the compiler.
Btw, it worked fine with Angular 7.
Could you please specify what exactly needs to be done to fix this issue?
Thanks in advance.

**Comment by AckerApple** [comment]
This is the first time I’m hearing of this issue. However, it’s not the first time I’ve heard of new issues arising from Angular 8.

I have no answer at this time

**Comment by solcre-gr** [comment]
Any update of this?

**Comment by AckerApple** [comment]
angular-file 2.0 has been just released today. It is mostly aimed at being on the newest angular, better distribution format, and bing ivy compatible.

Please give it a try at your earliest convenience please.

**Comment by solcre-gr** [comment]
Hi!
I tested it now and works perfectly!.
Thank u!

**Comment by manduriomane** [comment]
Hi, 

I have the same problem

Im'm using these packages:

- Angular: 10.1.4
- angular-file: 3.12
- @nguniversal/express-engine: 10.1.0

With Client rendering all works fine

When I compile with angular universal, I get this error:

**Comment by manduriomane** [comment]
Hi,

I have the same problem

I'm using these packages:

- Angular: 10.1.4
- angular-file: 3.12
- @nguniversal/express-engine: 10.1.0

With Client rendering all works fine

When I compile with angular universal, I get this error:
[
![Universal error](https://user-images.githubusercontent.com/25469100/95323459-7b372a80-089e-11eb-8f49-7d0cd9cdd3a1.JPG)
](url)

Here is main.js code:

```
ngf.ɵfac = function ngf_Factory(t) { return new (t || ngf)(_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵdirectiveInject"](_angular_core__WEBPACK_IMPORTED_MODULE_1__["ElementRef"])); };
ngf.ɵdir = _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵdefineDirective"]({ type: ngf, selectors: [["", "ngf", ""]], hostBindings: function ngf_HostBindings(rf, ctx) { if (rf & 1) {
        _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵlistener"]("change", function ngf_change_HostBindingHandler($event) { return ctx.onChange($event); });
    } }, inputs: { ngfFixOrientation: "ngfFixOrientation", fileDropDisabled: "fileDropDisabled", selectable: "selectable", lastInvalids: "lastInvalids", files: "files", file: "file", multiple: "multiple", accept: "accept", maxSize: "maxSize", lastBaseUrl: "lastBaseUrl" }, outputs: { directiveInit: "init", lastInvalidsChange: "lastInvalidsChange", lastBaseUrlChange: "lastBaseUrlChange", fileChange: "fileChange", filesChange: "filesChange" }, exportAs: ["ngf"], features: [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵNgOnChangesFeature"]] });
ngf.ctorParameters = () => [
    { type: _angular_core__WEBPACK_IMPORTED_MODULE_1__["ElementRef"] }
];

....


Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__decorate"])([
    Object(_angular_core__WEBPACK_IMPORTED_MODULE_1__["Input"])(),
    Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:type", File)
], ngf.prototype, "file", void 0);
```


How Can I fix this issue?

Thanks

Marco

**Comment by AckerApple** [comment]
“File” is an HTML5 element. You most likely need to install a types definition.

I think this package gets in definition from “@types/node” because it has a File definition. I could be wrong

**Comment by manduriomane** [comment]
Hi,

I downgraded to angular-file 3.0.1 version and now It works.

Marco

**Comment by AckerApple** [comment]
Ahhhhhhh no PR to make open source a better place?

Dang, hate to hear. Maybe I’ll help you out by adding a binding of “offsetX” and “offsetY” to allow setting to whatever you want. But I don’t need this so unsure when I will get to it
