### ISSUE TITLE
npm install --save-dev vs --save

### ISSUE THREAD

**Issue by digeomel** [AckerApple/angular-file#63]
The instructions for installation state that we should use:
`npm install angular-file --save-dev`
However, as this is a runtime feature, shouldn't it be
`npm install angular-file --save`
?

**Comment by AckerApple** [comment]
@Thieffen I see you liked this post and you also gave me the ng-packagr recommendation.

I'm wondering if you or @digeomel would argue or document further on changing from "--save-dev" to "--save" as my finding are conflicting and I am unconfident to recommend one from the other.

Thank you kindly.

**Comment by digeomel** [comment]
I think this stackoverflow discussion (and particular answer) describes it pretty well:
https://stackoverflow.com/a/42206389/134120
Now, in our case, we're using your component at runtime to allow uploading files with drag'n'drop. So, for this case, it's definitely `--save`.
However, if we were also using your component in our unit tests, then it would **also** be a dev dependency, and we would **also** need `--save-dev`.
According to the discussion on stackoverflow `--save-dev` seems to be a safe bet regardless of use, but imho it may still be misleading.

**Comment by MassiveHiggsField** [comment]
Guys, there shouldn't be any discussion here. But just to make it clear, "--save-dev" is only for stuff that is exclusively in use in unit tests, linting etc. Everything else is "--save". 

You would have to dream of a pretty specific scenario where you would only use this feature in dev. Maybe something like a custom generated unit test coverage report where a developer can manually add screenshots via an upload field provided by a separate angular application. But this would be an extremely exotic setup. 

The docs definitely should say to use "--save", no question. One last thing though, "--save" does not really exist anymore. Currently in use are: 

    common options: [--save-prod|--save-dev|--save-optional] [--save-exact] [--no-save]

"--save-prod" is the equivalent to the old "--save", which is also the default. So you could even remove it completely from the install command. 

I think the unopinionated approach that this package takes is very good, way better as "the other one", but the documentation really should be updated. There are dead links, confusing parts, that even for me as a senior developer were pretty confusing. But again other than the documentation, this package is really good, awesome job :+1:

**Comment by AckerApple** [comment]
@MassiveHiggsField Im looking forward to your pull request because I know when I mouth off, I’m willing to back it up.

**Comment by MassiveHiggsField** [comment]
lol capt. passive aggressive here. I won't update all your documentation, i don't know enough of your package. But i can make a pull request to remove the "--save-dev" if you really need me to....

ps: almost all code examples in your documentation are not usable, at least not without a bit of work.

**Comment by AckerApple** [comment]
No body is being passive aggressive. You’ve said your direct thoughts and so have I. Nothing indirect, passive, about it.

I’m led to believe you like to read yourself righteousness. So here you go: you are right. But you won’t do the work, for valid reasons and neither will I. It’s open source, participate or go ahead and just call shit out and be more of a Mr. Knowitall than Capt passive aggressive.

Fuck off. Not being passive in the least I hope. Fork me and make it your own.

Ps. This library was forked from someone else’s package I didn’t agree with. Look it up in the README, I give credit to the original package somewhere (GitHub has it tagged as a forked package). So fork off

**Comment by MassiveHiggsField** [comment]
Oh man, you are by far the rudest person i have ever encountered on this site. May everyone you work with have endless patience and a high tolerance for douche-baggery. no problem dude, to each his own. 

> No body is being passive aggressive. You’ve said your direct thoughts and so have I. Nothing indirect, passive, about it.

Hrhr you might wanna reread what passive aggressive even means :)

> I’m led to believe you like to read yourself righteousness. So here you go: you are right. 

Its a shame that you immediately think everyone is an asshole and only here to make you work. Who hurt you? 

> But you won’t do the work, for valid reasons and neither will I. It’s open source, participate or go > ahead and just call shit out and be more of a Mr. Knowitall than Capt passive aggressive.

Oh i have contributed to a lot of open source projects and everyone was way nicer than you. I would have done work on this repo here, but damn you are just to much of an ass ;). But i might fork it for me and if i fix all your problems, feel free to merge them back :)

> Fuck off. Not being passive in the least I hope. Fork me and make it your own.

Will do.... but fuck off, really. You justify your behaviour be calling it "being direct", but you might wanna think about how you treat other people. Not for my sake, but for everyone you are around. Damn, you really are the worst guy on this platform by far :D

> Ps. This library was forked from someone else’s package I didn’t agree with. Look it up in the README, I give credit to the original package somewhere (GitHub has it tagged as a forked package). So fork off

I know, i've used the original for angularJS and for the first newer angular versions, but your approach here, was way better than the one used in the original project. 

Man its a shame that you seem to be a good developer but just a broken person emotionally. I hope you get better.
