### ISSUE TITLE
excel mime type on accept attribute in windows 8.1 chrome and ie not working.

### ISSUE THREAD

**Issue by nurfgun** [AckerApple/angular-file#64]
```html
 <button ngfSelect 
        (filesChange)="onExcelUpload($event[0])"
        accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" 
        multiple="1"></button>
```

and onExcelUpload function never gets called in windows 7 thru 8.1 chrome 75 and ie11.
image/\*, video/\* works well in the same settings.

some users of our website reported this and I have confirmed it using browserstack.

changed it to .xlsx,.xls works.

THANKS FOR THIS GREATE LIBRARY!

**Comment by AckerApple** [comment]
Thank you for the report. Hopefully it will help others. At this time no further action will be taken. If you ever feel confident to make a fix then go ahead and make a pull request.

Thank you kindly for mentioning appreciating for this library. I use it a lot too and it’s a fun one.

**Comment by indelpro** [comment]
[8](https://github.com/AckerApple/angular-file/issues/64)
