### ISSUE TITLE
Cannot build with ivy enabled

### ISSUE THREAD

**Issue by wambowams** [AckerApple/angular-file#65]
Switching to ivy I get following error:
` ../node_modules/angular-file/file-upload/ngf.module.d.ts:1:22 - error TS-996003: Appears in the NgModule.exports of SharedModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class
1 export declare class ngfModule {`

**Comment by AckerApple** [comment]
Not sure what to do yet. I see these Ivy issue reports on many packages.

If anyone is in the know, lend a hand.

My company has put me on learning VueJs so Angular be taking a back seat in my life.

**Comment by Thieffen** [comment]
Maybe using [ng-packagr](https://github.com/ng-packagr/ng-packagr) when publishing to npm ?

See this answer from @jmesa-sistel here [https://github.com/primefaces/primeng/issues/7885#issuecomment-509636624](https://github.com/primefaces/primeng/issues/7885#issuecomment-509636624)

**Comment by AckerApple** [comment]
Thank you kindly.

It seems a few steps are required. Hopef

**Comment by digeomel** [comment]
I'm having the same issue, only my error is like this:

```
ERROR in ../node_modules/angular-file/file-upload/ngf.module.d.ts:1:22 - error TS-996002: Appears in the NgModule.imports of DocumentsModule, but could not be resolved to an NgModule class

1 export declare class ngfModule {
                       ~~~~~~~~~
```

**Comment by AckerApple** [comment]
Please try angular-file 2.0 at your earliest convenience. The demo is not built with ivy turned on. The core file are now built using latest angular and a much more proper distribution formatting has been applied.

I think you should be good to go. Please tell us about your experience.

**Comment by AckerApple** [comment]
@Thieffen ng-packagr was key to upgrading angular-file. Thank you so kindly for the tip.

**Comment by Thieffen** [comment]
> 
> 
> @Thieffen ng-packagr was key to upgrading angular-file. Thank you so kindly for the tip.

You did the hardest part of the job ;-)
Thank you for maintaining this usefull package.
