### ISSUE TITLE
ngfSelect doesn't work on my custom button

### ISSUE THREAD

**Issue by RezaRahmati** [AckerApple/angular-file#67]
I have a custom button component, ngfSelect doesn't work (show file selection dialog) on that, (no error on console) while it works on simple Button

Works
`<button #fileSelect="ngfSelect" ngfSelect (filesChange)="import($event)">xxx</button>`

Doesn't Work
```
<xy-button type="normal" text="Import" #fileSelect="ngfSelect" ngfSelect (filesChange)="import($event)">
</xy-button>
```

p.s
My button doesn't have `(click)` instead has `(onClick)`, not sure this could be the issue

update 
I confirm renaming onClick to click doesn't solve the issue

**Comment by AckerApple** [comment]
Yeah you’re like breaking the rules of Angular and how it works.

Don’t put it on your component definition. Find another way like wrap the component in a div or something

**Comment by RezaRahmati** [comment]
so what is the limitation of ngfSelect I mean which type of component it works on?

> breaking the rules of Angular 
Do you mean onClick?

**Comment by RezaRahmati** [comment]
I wrapped it in a span and still doesn't work

```
		<span #fileSelect="ngfSelect" ngfSelect (filesChange)="import($event)"
			accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
			<xy-button type="normal" text="Import">
			</xy-button>
		</span>
```

**Comment by RezaRahmati** [comment]
OK, I wrapped it in a span. and works now

**Comment by RezaRahmati** [comment]
Also thanks for very fast response
