### ISSUE TITLE
[bug] _acceptFilter filters mxf files when accept='.mxf,video/*'

### ISSUE THREAD

**Issue by amitport** [AckerApple/angular-file#7]

**Comment by AckerApple** [comment]
Is maybe your filter supposed to be "mxf,video/*" and NOT ".mxf,video/*"

**Comment by AckerApple** [comment]
I think the dot at the start is your issue. I googled mxf video mime type and didnt see your declaration:

https://stackoverflow.com/questions/19107685/safari-input-type-file-accept-video-ignores-mp4-files

**Comment by AckerApple** [comment]
Regardless, I have determined a fix is needed because mime types can contain dots as seen in this mime type list:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

This library attempts to use a regular expression to match mime types to input accept attributes. Thus stars are converted and now so too must dots be casted before used as a regular expression match.

**Comment by AckerApple** [comment]
Link to self, where code adjustment needs to take place:
https://github.com/AckerApple/angular-file/blob/development/src/file-upload/FileUploader.class.ts#L327

**Comment by AckerApple** [comment]
This library is also not parsing comma separated definitions.

**Comment by AckerApple** [comment]
It does parse comma separated lists BUT does NOT take into consideration the list might contain file extensions and NOT just mime types

**Comment by AckerApple** [comment]
UPDATED!

The code that checks accept type, has been altered to better support mime type checking:
https://github.com/AckerApple/angular-file/blob/development/src/file-upload/FileUploader.class.ts#L331

Please update to version 0.3.4 and let me know what you see.

A unit test has been created for this:
https://github.com/AckerApple/angular-file/blob/development/src/file-upload/FileUploader.class.spec.ts#L21

Please check the unit test to see if you you are in-fact covered as expected. I've never seen file type mxf nor is it listed in popular file types.

**Comment by amitport** [comment]
wow, that was quick, thanks! I'll verify tomorrow

btw, the format I used is part of the HTML standard for `<input type="file">` (dot before extension, comma separators, and `<media-type>/*` catch all) [Limiting accepted file types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Limiting_accepted_file_types)

btw2, MXF is widely used in the professional media industry (it's not so poplar for home use, browsers do not natively filter it with `video/*`, and that's why I use `.mxf,video/*`).

**Comment by AckerApple** [comment]
First, thanks for the info. I had not done enough home work on the accept attribute until you submitted this issue and then I realized how bad I had assumed things worked.

Second, I've just started posting YouTube videos and relearning the strings attached to video compressions. I'll put mxf on my radar but yeah my use is home use for pinball videos and work demos: https://www.youtube.com/channel/UCRCKyvCAnSjVSJoRfdySfjg

Third, I'm glad you like the fast response time (and can deal with the abundant amount of fast comments). I want to live, breathe, and promote Open Source programming. Although, I am looking to advance my paying career. Please keep an ear out for this South Florida programmer. My resume here: https://github.com/AckerApple/resume

Be good. Close this issue, once satisfied.

**Comment by amitport** [comment]
almost worked, I had to assign the file.type from the extension in file.name.
https://github.com/AckerApple/angular-file/pull/8

annoyingly file.type is empty for 'mxf' files (using chrome and windows 7)

**Comment by AckerApple** [comment]
If this issue is completed, please close. Lets continue this separate issue, of what seems to be mime types being reported as empty-string, in issue number 8

**Comment by AckerApple** [comment]
Moving at a thousand miles and hour, I missed that @amitport was submitting a pull request and NOT another issue. This issue could have remained opened, my apologies.

Regardless, I have released a fix. Annnnnnnnnd an extra thank you to @amitport for attempting to contribute with a pull request as that is the highest level of giving back to a package.

**Comment by amitport** [comment]
I can confirm this issue is fixed with angular-file@0.3.5. Thanks!
