### ISSUE TITLE
Outlook add-in client is crashed when picking files from windows file picker

### ISSUE THREAD

**Issue by eladco898** [AckerApple/angular-file#71]
Outlook(IE) is crashed sometimes when using this module inside add-in.
The add-in is running angular7, a standard client-side application. 
Any idea?
Window version: Windows 10 Pro 1903
Outlook version: 1910
angular-file version: 0.5.9
Elad

**Comment by AckerApple** [comment]
Looks like you have an old version of everything. That’s my guess

**Comment by eladco898** [comment]
I have updated your lib version.
Now I am using  angular-file 2.0.0
Windows version is updated lastly
Ant other ideas?
