### ISSUE TITLE
Error when creating in Ivy mode　

### ISSUE THREAD

**Issue by kenji-iiii** [AckerApple/angular-file#72]
Error when creating in Ivy mode　

"angular-file": "^2.0.0",

```
0% compiling
Compiling angular-file : es2015 as esm2015
ERROR in No suitable injection token for parameter 'element' of class 'ngf'.
no type or decorator
```

i can compile if not in lvy mode .

**Comment by kenji-iiii** [comment]
#

**Comment by Mustardapp** [comment]
I am having the same error

**Comment by priscilalima** [comment]
I am having the same error

**Comment by AckerApple** [comment]
I recently updated this package drastically to have better distribution. I will need assistance to know what to change to support Ivy.

**Comment by darvids0n** [comment]
The recommendation from Angular devteam is to set "enableIvy": false in your `tsconfig.app.json` for now.

> If you are a library author, you should keep using the View Engine compiler as of version 9. By having all libraries continue to use View Engine, you will maintain compatibility with default v9 applications that use Ivy, as well as with applications that have opted to continue using View Engine.
https://next.angular.io/guide/ivy

**Comment by darvids0n** [comment]
I created #74 to fast-track this change if you want it

**Comment by AckerApple** [comment]
This package has now been built on Angular 9.

Version 3.0.0 of this package has been tested to work with production building with Ivy turned on

Please try and let me know your results

**Comment by darvids0n** [comment]
Not getting any compile issues with AOT compilation! I think we can close this one.

**Comment by AckerApple** [comment]
@darvids0n thank you so extra very much
