### ISSUE TITLE
Custom files binding not working

### ISSUE THREAD

**Issue by uvcreation** [AckerApple/angular-file#73]
I have requirement where we have one extra field -> the input for "file description" where User could provide description for file.

As I could see, you are allow to bind [(files)] but in my case, I have to create the custom class with having one addition property of "file_description" and bind it to [(files)].

But unfortunately It is not working since [(files)] expecting to bind Files class.

Is there any possibility of binding custom class? could anyone please help me with that?

**Comment by uvcreation** [comment]
@AckerApple I got solution for above issue and it's resolved. I really appreciate your work.

**Comment by uvcreation** [comment]
@AckerApple I need to limit the count of file upload, do we have any option for that?

**Comment by AckerApple** [comment]
Yes just limit the length of your array. Such an easy solution that we’ve never wanted to make a custom one.

files.length = 2

**Comment by uvcreation** [comment]
@AckerApple Cool! thank you for your help.

**Comment by uvcreation** [comment]
@AckerApple I have problem with the file upload. If I upload 2 files of size 23 MB then it throws 413 or 404 status code from server. As far as I know it's because of the limitation of server. 

Presently maxSize limit checks for single file. Is it possible to limit the size for combine files?
