### ISSUE TITLE
map files not included in the build (2.0.0 || 3.0.0)

### ISSUE THREAD

**Issue by Betalos** [AckerApple/angular-file#76]
The library does not include the map files wich make the cli to throw warnings:
```bash
WARNING in The external map file specified in the source code comment "/node_modules/angular-file/fesm2015/angular-file.js.map" was not found on the file system.
```

**Comment by Shoe2** [comment]
i have the same issue

**Comment by Shoe2** [comment]
Does not seem to effect functionality of the limited use case we have implemented, just an annoying warning message

**Comment by AckerApple** [comment]
Understood. I will look into further within about a week max

**Comment by AckerApple** [comment]
I took a look, I don't know why no map files.

Hey listen, I'm honestly tired of keeping up with the few Angular packages I have. It's not rewarding in nearly any sense.

Please seek alternatives like this package here looks popular: https://www.npmjs.com/package/ngx-file-drop

**Comment by Shoe2** [comment]
Maybe just take the packages down then? If its published people are gonna use it

**Comment by AckerApple** [comment]
Got any other ideas. I know many packages no longer maintained. I’d put a message of not maintaining but i do keep it functioning bare minimum in

**Comment by Shoe2** [comment]
https://github.com/angular/angular-cli/issues/8662

Maybe try the command in here? it looks to force generate source maps.

**Comment by Shoe2** [comment]
more options
https://blog.sentry.io/2018/10/18/4-reasons-why-your-source-maps-are-broken

**Comment by Betalos** [comment]
#85 was added

**Comment by Betalos** [comment]
@AckerApple the issue of the map still exist (I think the build cmd should be 'npm run build:prod')

**Comment by AckerApple** [comment]
The build:prod is what’s run as seen here: https://github.com/AckerApple/angular-file/blob/development/package.json

**Comment by Betalos** [comment]
@AckerApple ah i see the issue. The issue is with the .gitignore it has a *.js.map so it would never be commited.

**Comment by AckerApple** [comment]
Ohhhhh, damn this whole time............ shoot. Aight. Either I’ll get that fixed or issue the PR Andy I get to it

**Comment by Betalos** [comment]
@AckerApple sure thing. i'll PR now.

**Comment by Betalos** [comment]
PR added.

**Comment by AckerApple** [comment]
I set a reminder to publish this later this evening
