### ISSUE TITLE
Please add  documentation for (filesChange) 

### ISSUE THREAD

**Issue by Zadvornyi** [AckerApple/angular-file#91]

**Comment by AckerApple** [comment]
[(filesChange)]

The documentation already has this. If you want it spelled out more, issue a pull request against the README.md

**Comment by Zadvornyi** [comment]
Hello,
Sorry, but I could not find documentation about [(filesChange)], at README.md.

**Comment by AckerApple** [comment]
You are basically asking me one of the most basic Angular questions (aka how does Input/Output decorators work)

[(files)]=“model”

(filesChange)=“model=$event”
