### ISSUE TITLE
is it possible to upload angular dependecies to v11?

### ISSUE THREAD

**Issue by nevernet** [AckerApple/angular-file#92]

**Comment by nevernet** [comment]
```
 Package "angular-file" has an incompatible peer dependency to "@angular/common" (requires "^9.1.9" (extended), would install "11.0.0").
                  Package "angular-file" has an incompatible peer dependency to "@angular/core" (requires "^9.1.9" (extended), would install "11.0.0").
```

**Comment by AckerApple** [comment]
Sorta confirmed, does seem ng11 is complaining about whatever version this was built under.

I will be in touch

**Comment by thatcort** [comment]
I just tried using it with Angular 11 and got the following error messages:

```
Error: node_modules/angular-file/file-upload/ngf.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (angular-file) which declares ngfModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    1 export declare class ngfModule {
                           ~~~~~~~~~
```

**Comment by AckerApple** [comment]
I fell asleep on this issue. Sorry. I’ll get to it relatively soon

**Comment by AckerApple** [comment]
Try now. Version 3.3.0

**Comment by nevernet** [comment]
Great, thank you 👍

**Comment by thatcort** [comment]
Hi, the library does indeed work with ng11, but the peer dependencies on @angular/common and @angular/core need updating. This prevents updating using `ng update`. It's currently set to `^9.1.9`

**Comment by AckerApple** [comment]
Please check again. I’m seeing version 10 and not 9

https://github.com/AckerApple/angular-file/blob/development/package.json

I will look at perhaps jumping to version 11 but I swear I did that (maybe it didn’t push)

all check everything out tomorrow Jan 5th

**Comment by thatcort** [comment]
In my node modules folder I see version 3.3.0 and the peer dependencies have version ^9.1.9.

In the package.json you linked to I don't see any peer dependencies listed at all(?)

**Comment by AckerApple** [comment]
Thank you for commenting again. I think I see what is going on here

**Comment by AckerApple** [comment]
fixed
