### ISSUE TITLE
Cannot read property 'nativeElement' of undefined - Angular 5 

### ISSUE THREAD

**Issue by HariPrasad-1493** [AckerApple/angular-file#93]
Hi , im trying to implement the directive as below & show a small preview as well on upload , but facing this issue 
<button ngfSelect [(file)]="imgFile" accept="image/*" (click)="imageUploader.click()" >Upload</button>
                        <input  type="file" style="display: none !important" #imageUploader (change)="imageUpload($event)" />
                        <p>
                          <img *ngIf="!imgFile" class="img-thumbnail" src="public/img/logo.jpg" />
                          <img *ngIf="imgFile" class="img-thumbnail" src="imgFile" />
                        </p>

problem from console points at & Im unable to show the image as well
paramFileElm() {
        if (this.fileElm)
            return this.fileElm; //already defined
        //elm is a file input
        const isFile = isFileInput(this.element.nativeElement); ===> this line throws console error 
        if (isFile)}

**Comment by AckerApple** [comment]
Upgrade from ng5
