### ISSUE TITLE
ngfFixOrientation breaking some images

### ISSUE THREAD

**Issue by pygoscelis13** [AckerApple/angular-file#95]
I have the problem that some of my images were somehow damaged during the upload. Not just any pictures, but those taken by a specific camera. It turns out, the problem is somehow with the routine you enable with ngfFixOrientation. 

You can reproduce the error already with the demo page and the attached files. They are both done with the same mobile / camera, only one is portrait, the other landscape. I put them in a zip-file to keep them the original way...
[images.zip](https://github.com/AckerApple/angular-file/files/6124937/images.zip)

However, the one ending on 36 can not be handled by the function. The image gets somehow smaller and cannot be shown or used anymore. 

For my case it might be working with simply switching the orientation fix, but I thought it might be worth mentioning it nonetheless.

**Comment by AckerApple** [comment]
For now at this time I can only offer to say try using `[ngfFixOrientation]=“false”`

**Comment by pygoscelis13** [comment]
Yes, I will most likely do that - as I said, I can get along without the orientation fix.

Still weird - I tried with pictures from other cameras and they do not pose a problem. Those pics come from a Samsung mobile, so no niche product either.
