### ISSUE TITLE
3.5.3 ngfSelect not respecting multiple

### ISSUE THREAD

**Issue by Betalos** [AckerApple/angular-file#97]
I found out the ngfSelect if a div won't take the multiple or accept attrs into account when opening file dialog
```html
<div class="upload-section" fxFlex fxLayout="column" ngfDrop ngfSelect multiple [files]='files' (filesChange)="handleItems($event, true)" (validDragChange)="hasBaseDropZoneOver = $event"
         [ngClass]="{'file-over': hasBaseDropZoneOver}">
    UPLOAD BLOCK
</div>
```

**Comment by AckerApple** [comment]
For now, use [multiple]=true OR put a value in your multiple=“1”

it’s reading your multiple as empty string and thinks it’s false

**Comment by Betalos** [comment]
Hello @AckerApple.
Thanks for the quick replay, I gave it a try and the isue persists.
```html
<div class="upload-section" fxFlex fxLayout="column" ngfDrop ngfSelect [multiple]="true"
     [ngClass]="{'file-over': hasBaseDropZoneOver}" (validDragChange)="hasBaseDropZoneOver = $event"
     [accept]="'application/pdf,image/*'" [(files)]="files">
         UPLOAD SECTION
</div>
```

**Comment by AckerApple** [comment]
I wonder if it has to do with you using both `ngfDrop` and `ngfSelect` together. I’ve never done that as it causes two Directive to run at same time... Try this from the docs but alter it for your needs:

```

// Combo Drop Select

<div ngfDrop selectable="1" multiple="1"
  [(files)]="files"
  [(validDrag)]="validComboDrag"
  [(invalidDrag)]="invalidComboDrag"
  [ngClass]="{'goodDragClass':validComboDrag, 'badDragClass':invalidComboDrag}"
>
  Combo drop/select zone
</div>
```

**Comment by AckerApple** [comment]
I have added labels for future referencing and memory jogging that I think we have an invalid usage going on here and that perhaps we need to console warn when two ngf directives are attached to one element

**Comment by Betalos** [comment]
Well I tried removing one of the directives, yet the issue still persists (I think is a regression of some sort), before 3.5.* version it was working.
```html
<div class="upload-section" fxFlex fxLayout="column" ngfSelect [multiple]="true"
   [ngClass]="{'file-over': hasBaseDropZoneOver}"
   [accept]="'application/pdf,image/*'" [(files)]="files">
   UPLOAD AREA
</div>
```

**Comment by AckerApple** [comment]
I was execting ngfDrop not ngfSelect in above example

I will try multiple selecting today on angular-file demo page:
https://ackerapple.github.io/angular-file/

**Comment by AckerApple** [comment]
The gh-pages demo is still stuck on 3.5.2 and even though I have pushed, it's not updating to the latest code.

To test, I ran the following commands you could run too, for launching the angular-file demo locally:
```
git clone http://github.com/ackerapple/angular-file -b gh-pages gh-pages && cd gh-pages && npm install && npm run start
```

The angular-file demo includes multiple file inputs, including a multi-file input which appears as working.
